name: AI_Predictions
channels:
  - conda-forge
dependencies:
  - jupyter 
  - matplotlib >= 3.8
  - openpyxl >= 3.0
  - pandas >= 2.0
  - pandas-datareader
  - pip >= 24.0
  - pyarrow 
  - py-xgboost
  - python = 3.12
  - scikit-learn >= 1.4
  - sqlalchemy
  - xgboost >= 2.0.3
  - pmdarima >= 2.0
  - pip:
      - cinemagoer
      - lxml
      - pynytimes
      - pyjokes == 0.6.0
      - plotly == 5.24.0
      - seaborn == 0.13.2